name: Build Unsigned IPA

# 手动触发，或者你也可以改成 push 到某分支、PR 或 release 时自动触发
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'
      sdk:
        description: 'SDK to build (iphoneos or iphonesimulator)'
        required: false
        default: 'iphoneos'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        # 在 bash 环境下执行；set -e 看到错误即停止
        shell: bash {0}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # 如果你用 CocoaPods，请取消下面两步的注释：
      #- name: Install CocoaPods
      #  run: |
      #    brew install cocoapods
      #    pod install --repo-update
      #
      #- name: Open workspace
      #  run: echo "We'll build the .xcworkspace instead of .xcodeproj"

      - name: Build .app without code signing
        run: |
          set -e
          xcodebuild clean build \
            -project MyApp.xcodeproj \
            -target MyApp \
            -configuration ${{ github.event.inputs.configuration }} \
            -sdk ${{ github.event.inputs.sdk }} \
            CODE_SIGNING_ALLOWED=NO \
            BUILD_DIR="$PWD/build" \
            BUILD_ROOT="$PWD/build"
            INFOPLIST_FILE="Info.plist"

      - name: Package .app into unsigned IPA
        run: |
          set -e
          mkdir -p build/ipa/Payload
          # Copy .app
          cp -R build/${{ github.event.inputs.configuration }}-${{ github.event.inputs.sdk }}/MyApp.app build/ipa/Payload/
          cd build/ipa
          # Zip into .ipa
          zip -qr MyApp-unsigned.ipa Payload

      - name: Upload unsigned IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-unsigned.ipa
          path: build/ipa/MyApp-unsigned.ipa